// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCl9eiQ_L5SRRawlLfOcdCU42TFzeEtk8',
    appId: '1:60935317588:web:036a1493bc71f9a4e365c1',
    messagingSenderId: '60935317588',
    projectId: 'ice-helphand',
    authDomain: 'ice-helphand.firebaseapp.com',
    storageBucket: 'ice-helphand.appspot.com',
    measurementId: 'G-V3SRW5VJS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQJqfUUOb1ngS5c-LTuZUyQhYTsq8BQUo',
    appId: '1:83178293100:android:ed01fdcca96bfbaebb9549',
    messagingSenderId: '83178293100',
    projectId: 'helpinghand-d5887',
    storageBucket: 'helpinghand-d5887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnRFRS3HYX-EJCgiISrvpN7-x_oTSQ_lE',
    appId: '1:83178293100:ios:dc5cfe73b5709b4abb9549',
    messagingSenderId: '83178293100',
    projectId: 'helpinghand-d5887',
    storageBucket: 'helpinghand-d5887.appspot.com',
    iosBundleId: 'com.example.iceHelphand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfUnUF3KSC7MyXo0dTUYKR7Bf_ossxPO4',
    appId: '1:60935317588:ios:4068b7b48e401111e365c1',
    messagingSenderId: '60935317588',
    projectId: 'ice-helphand',
    storageBucket: 'ice-helphand.appspot.com',
    androidClientId: '60935317588-8tqkitlis7lnmsburmcgiaic9qmglp0g.apps.googleusercontent.com',
    iosClientId: '60935317588-colj1c8o9mvfgu4b2eljoc36pks2fko1.apps.googleusercontent.com',
    iosBundleId: 'com.example.iceHelphand',
  );
}